-- Tabela 'vehicles'
CREATE TABLE public.vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  owner_id BIGINT NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  plate TEXT NOT NULL,
  chassis TEXT,
  renavam TEXT,
  brand TEXT,
  model TEXT,
  year_manufacture INTEGER,
  year_model INTEGER,
  color TEXT,
  fuel_type TEXT,
  licensing_expiration_date DATE,
  image_urls TEXT[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Agências podem gerenciar seus próprios veículos" ON public.vehicles 
FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);


-- Tabela 'services'
CREATE TABLE public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  client_id BIGINT NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  vehicle_id BIGINT NOT NULL REFERENCES public.vehicles(id) ON DELETE CASCADE,
  payer_client_id BIGINT REFERENCES public.clients(id),
  name TEXT NOT NULL,
  status TEXT,
  due_date DATE,
  price NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Agências podem gerenciar seus próprios serviços" ON public.services 
FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);


-- Tabela 'transactions'
CREATE TABLE public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  client_id BIGINT REFERENCES public.clients(id),
  service_id BIGINT REFERENCES public.services(id),
  description TEXT NOT NULL,
  category TEXT,
  date DATE NOT NULL,
  due_date DATE,
  amount NUMERIC NOT NULL,
  type TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Agências podem gerenciar suas próprias transações" ON public.transactions 
FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);