// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dipmnpqnxziougeqtmyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpcG1ucHFueHppb3VnZXF0bXluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4NjUyMDMsImV4cCI6MjA3NzQ0MTIwM30.IbTQFVXjEO1gmdQumMGJRaAErtZ4tu8bCIZ0F1QO-jQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);